DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    email     VARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_description VARCHAR(1024)                  NOT NULL,
    requestor_id        INT REFERENCES users (user_id) NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name   VARCHAR(255)                   NOT NULL,
    description VARCHAR(1024)                  NOT NULL,
    available   BOOLEAN                        NOT NULL,
    owner_id    INT REFERENCES users (user_id) NOT NULL,
    request_id  INT
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE    NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE    NOT NULL,
    item_id    INT REFERENCES items (item_id) NOT NULL,
    booker_id  INT REFERENCES users (user_id) NOT NULL,
    status     VARCHAR(64)                    NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(512)                  NOT NULL,
    item_id      INT REFERENCES items (item_id) NOT NULL,
    author_id    INT REFERENCES users (user_id) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE    NOT NULL
);
